const types = {
    APPLICATIONS_LOAD_SUCCESS:"APPLICATIONS_LOAD_SUCCESS",
    APPLICATIONS_LOAD_ERROR: "APPLICATIONS_LOAD_ERROR",
    APPLICATIONS_LOAD_LOADING: "APPLICATIONS_LOAD_LOADING,"
}
export default types;
