const types = {
    APPLICATIONS_LOAD_SUCCESS:"APPLICATIONS_LOAD_SUCCESS",
    APPLICATIONS_LOAD_ERROR: "APPLICATIONS_LOAD_ERROR",
    APPLICATIONS_LOAD_LOADING: "APPLICATIONS_LOAD_LOADING",
    APPLICATIONS_FOR_SIFT_LOAD_SUCCESS: "APPLICATIONS_FOR_SIFT_LOAD_SUCCESS",
    UPCOMING_INTERVIEWS_LOAD_SUCCESS: "UPCOMING_INTERVIEWS_LOAD_SUCCESS",
    INTERVIEWS_TO_SCORE_LOAD_SUCCESS: "INTERVIEWS_TO_SCORE_LOAD_SUCCESS",
    APPLICATIONS_APPLY_FILTER: "APPLICATIONS_APPLY_FILTER",
    SEARCH_FILTER_CHANGED: "SEARCH_FILTER_CHANGED",
}
export default types;
